export const channelOptions = [
    { name: "Channel 1", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 1 will be the first fader to the right of that button" },
    { name: "Channel 2", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 2 will be the second fader to the right of that button" },
    { name: "Channel 3", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 3 will be the third fader to the right of that button" },
    { name: "Channel 4", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 4 will be the fourth fader to the right of that button" },
    { name: "Channel 5", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 5 will be the fifth fader to the right of that button" },
    { name: "Channel 6", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 6 will be the sixth fader to the right of that button" },
    { name: "Channel 7", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 7 will be the seventh fader to the right of that button" },
    { name: "Channel 8", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 8 will be the eighth fader to the right of that button" },
    { name: "Channel 9", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 9 will be the eighth fader to the left of the center column of buttons" },
    { name: "Channel 10", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 10 will be the seventh fader to the left of the center column of buttons" },
    { name: "Channel 11", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 11 will be the sixth fader to the left of the center column of buttons" },
    { name: "Channel 12", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 12 will be the fifth fader to the left of the center column of buttons" },
    { name: "Channel 13", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 13 will be the fourth fader to the left of the center column of buttons" },
    { name: "Channel 14", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 14 will be the third fader to the left of the center column of buttons" },
    { name: "Channel 15", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 15 will be the second fader to the left of the center column of buttons" },
    { name: "Channel 16", findText: "Press the CH 1-16 Button near the bottom left of the console and Channel 16 will be the first fader to the left of the center column of buttons" },
    { name: "Channel 17", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 17 will be the first fader to the right of that button" },
    { name: "Channel 18", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 18 will be the second fader to the right of that button" },
    { name: "Channel 19", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 19 will be the third fader to the right of that button" },
    { name: "Channel 20", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 20 will be the fourth fader to the right of that button" },
    { name: "Channel 21", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 21 will be the fifth fader to the right of that button" },
    { name: "Channel 22", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 22 will be the sixth fader to the right of that button" },
    { name: "Channel 23", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 23 will be the seventh fader to the right of that button" },
    { name: "Channel 24", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 24 will be the eighth fader to the right of that button" },
    { name: "Channel 25", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 25 will be the eighth fader to the left of the center column of buttons" },
    { name: "Channel 26", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 26 will be the seventh fader to the left of the center column of buttons" },
    { name: "Channel 27", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 27 will be the sixth fader to the left of the center column of buttons" },
    { name: "Channel 28", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 28 will be the fifth fader to the left of the center column of buttons" },
    { name: "Channel 29", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 29 will be the fourth fader to the left of the center column of buttons" },
    { name: "Channel 30", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 30 will be the third fader to the left of the center column of buttons" },
    { name: "Channel 31", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 31 will be the second fader to the left of the center column of buttons" },
    { name: "Channel 32", findText: "Press the CH 17-32 Button near the bottom left of the console and Channel 32 will be the first fader to the left of the center column of buttons" },
    { name: "Aux In 1", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and Aux 1 will be the first fader to the right of that button (This channel is Green and labeled `Aux1`)" },
    { name: "Aux In 2", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and Aux 2 will be the second fader to the right of that button (This channel is Green and labeled `Aux2`)" },
    { name: "Aux In 3", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and Aux 3 will be the third fader to the right of that button (This channel is Green and labeled `Aux3`)" },
    { name: "Aux In 4", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and Aux 4 will be the fourth fader to the right of that button (This channel is Green and labeled `Aux4`)" },
    { name: "Aux In 5", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and Aux 5 will be the fifth fader to the right of that button (This channel is Green and labeled `Aux5`)" },
    { name: "Aux In 6", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and Aux 6 will be the sixth fader to the right of that button (This channel is Green and labeled `Aux6`)" },
    { name: "FX Return 1", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and FX 1 Returns L and R will be the seventh and eighth fader to the left of the center column of buttons. Do note that they are in stereo so moving one fader will change the other for you" },
    { name: "FX Return 2", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and FX 2 Returns L and R will be the fifth and sixth fader to the left of the center column of buttons. Do note that they are in stereo so moving one fader will change the other for you" },
    { name: "FX Return 3", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and FX 3 Returns L and R will be the third and fouth fader to the left of the center column of buttons. Do note that they are in stereo so moving one fader will change the other for you." },
    { name: "FX Return 4", findText: "Press the AUX IN / USB FX RETURNS Button near the bottom left of the console and FX 4 Returns L and R will be the first and second fader to the left of the center column of buttons. Do note that they are in stereo so moving one fader will change the other for you." }
]

export const busOptions = [
    { name: "MixBus 1", findText: "Press the BUS 1-8 button in the middle of the board between the faders and press Select the first fader to the right of that button" },
    { name: "MixBus 2", findText: "Press the BUS 1-8 button in the middle of the board between the faders and press Select the second fader to the right of that button" },
    { name: "MixBus 3", findText: "Press the BUS 1-8 button in the middle of the board between the faders and press Select the third fader to the right of that button" },
    { name: "MixBus 4", findText: "Press the BUS 1-8 button in the middle of the board between the faders and press Select the fourth fader to the right of that button" },
    { name: "MixBus 5", findText: "Press the BUS 1-8 button in the middle of the board between the faders and press Select the fifth fader to the right of that button" },
    { name: "MixBus 6", findText: "Press the BUS 1-8 button in the middle of the board between the faders and press Select the sixth fader to the right of that button" },
    { name: "MixBus 7", findText: "Press the BUS 1-8 button in the middle of the board between the faders and press Select the seventh fader to the right of that button" },
    { name: "MixBus 8", findText: "Press the BUS 1-8 button in the middle of the board between the faders and press Select the eighth fader to the right of that button" },
    { name: "MixBus 9", findText: "Press the BUS 9-16 button in the middle of the board between the faders and press Select the first fader to the right of that button" },
    { name: "MixBus 10", findText: "Press the BUS 9-16 button in the middle of the board between the faders and press Select the second fader to the right of that button" },
    { name: "MixBus 11", findText: "Press the BUS 9-16 button in the middle of the board between the faders and press Select the third fader to the right of that button" },
    { name: "MixBus 12", findText: "Press the BUS 9-16 button in the middle of the board between the faders and press Select the fourth fader to the right of that button" },
    { name: "MixBus 13", findText: "Press the BUS 9-16 button in the middle of the board between the faders and press Select the fifth fader to the right of that button" },
    { name: "MixBus 14", findText: "Press the BUS 9-16 button in the middle of the board between the faders and press Select the sixth fader to the right of that button" },
    { name: "MixBus 15", findText: "Press the BUS 9-16 button in the middle of the board between the faders and press Select the seventh fader to the right of that button" },
    { name: "MixBus 16", findText: "Press the BUS 9-16 button in the middle of the board between the faders and press Select the eighth fader to the right of that button" }
]

export const matrixOptions = [
    {name: "Matix 1", findText: "Press the MATRIX 1-6 MAIN C button in the middle of the board between the 2 banks of faders. Matrix 1 is the first fader to the right of that button"},
    {name: "Matix 2", findText: "Press the MATRIX 1-6 MAIN C button in the middle of the board between the 2 banks of faders. Matrix 2 is the second fader to the right of that button"},
    {name: "Matix 3", findText: "Press the MATRIX 1-6 MAIN C button in the middle of the board between the 2 banks of faders. Matrix 3 is the third fader to the right of that button"},
    {name: "Matix 4", findText: "Press the MATRIX 1-6 MAIN C button in the middle of the board between the 2 banks of faders. Matrix 4 is the fourth fader to the right of that button"},
    {name: "Matix 5", findText: "Press the MATRIX 1-6 MAIN C button in the middle of the board between the 2 banks of faders. Matrix 5 is the fifth fader to the right of that button"},
    {name: "Matix 6", findText: "Press the MATRIX 1-6 MAIN C button in the middle of the board between the 2 banks of faders. Matrix 6 is the sixth fader to the right of that button"}
]